version: '3.7'

services:
  java:
    container_name: java
    build:
      context: .
      dockerfile: ./dockerized_config/java/Dockerfile
    environment:
      - TZ=Asia/Shanghai
    restart: always
    depends_on: 
      - db
    volumes:
      - ./dockerized_config/java/logs:/logs
      - ./dockerized_config/java/application.yml:/application.yml
      - ./dockerized_config/java/logback.xml:/logback.xml
    ports:
      - 5000:8888

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./dockerized_config/nginx/Dockerfile
    environment:
      - TZ=Asia/Shanghai
    restart: always
    depends_on: 
      - java
    volumes:
      - ./dockerized_config/nginx/80.conf:/etc/nginx/conf.d/default.conf
      # - ./dockerized_config/nginx/443.conf:/etc/nginx/conf.d/default.conf
      - ./dockerized_config/nginx/ssl:/etc/nginx/ssl
      - ./dockerized_config/nginx/html:/var/www/wish_dist
    ports:
      - 80:80
      # - 443:443

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai 
      - MYSQL_ROOT_PASSWORD=wishwish
      - MYSQL_DATABASE=pray
      - MYSQL_USER=wish
      - MYSQL_PASSWORD=wishwish
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dockerized_config/mysql/db_data:/var/lib/mysql
      - ./dockerized_config/mysql/init_mysql.sql:/docker-entrypoint-initdb.d/init.sql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
