spring:
  application:
    name: pray
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/wish?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema:
    #    classpath: sql/sends-delisting.sql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
# 应用服务 WEB 访问端口 本地8080 部署8443
server:
  port: 8888

swagger:
  enable : true

app:
  id: your wx appId
  secret: your wx appSecret